# Generated by Django 4.2.11 on 2025-11-21 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('prioridad', models.CharField(choices=[('Crítica', 'Crítica'), ('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=16)),
                ('estado', models.CharField(choices=[('Lista', 'Lista'), ('En revisión', 'En revisión'), ('Hecha', 'Hecha')], default='Lista', max_length=20)),
                ('etiqueta', models.CharField(blank=True, max_length=64)),
                ('puntos', models.IntegerField(blank=True, null=True)),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('listaParaSprint', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('desc', models.TextField(blank=True)),
                ('tag', models.CharField(max_length=64)),
                ('proyecto', models.CharField(max_length=64)),
                ('favorito', models.BooleanField(default=False)),
                ('clones', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
