# Generated by Django 4.2.11 on 2025-11-21 17:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sprint.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('iniciales', models.CharField(max_length=8)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='SprintColumn',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('orden', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=160)),
                ('puntos', models.IntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('owner', models.CharField(blank=True, max_length=8)),
                ('progreso', models.JSONField(default=sprint.models.default_progreso)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('checklist', models.JSONField(blank=True, default=sprint.models.default_checklist)),
                ('storyId', models.CharField(blank=True, max_length=32, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='sprint.sprintcolumn')),
            ],
        ),
    ]
